### ISSUE TITLE
The website is soo smooth, great job!

### ISSUE THREAD

**Issue by Sandile-Dev01** [lakshaybhushan/lakshb.me#1]
I love how smooth the site is, it gives a satisfying mood when you scroll.

**Projects section**

- I feel like adding the technologies you used for each project would be a sensible feature.
- I noticed that when I animate over the project, the color changes and that gave me a thought that the whole container was click-able, which in my disappointment was not.
- Wrapping the whole project item container with the `a` tag and removing the small 'link icon' would be even more efficient for UX (user experience)

Overall the portfolio is slick, and the color palette is on point. I also like how you magnified the arrow-to-top icon, it gives nice `hierarchy` to the user.

**Comment by lakshaybhushan** [comment]
Hey!! Thank you for taking the time to explore my portfolio and providing valuable feedback. I'm glad to hear that you enjoyed the smooth scrolling and found the colour palette appealing. Your insights are greatly appreciated.

Regarding the projects section, I wanted to clarify that the entire container is clickable, including the project description. The presence of the "link icon" was intended to help users recognize clickable elements, but I understand your point about potential confusion.

Additionally, I agree that including the technologies used for each project would enhance the information provided. I'll definitely look into integrating that feature to give a more comprehensive overview of my work as I'm working on the V2 of my website.

Thank you once again for your valuable feedback :)
